

-- get all declared scripts
SELECT
    ii.NAME,
    ii.DESCRIPTION,
    ii.SCRIPTEXISTS
FROM INTERACTIONSCRIPT ii;


-- get prepared scripts
SELECT
    ii.NAME,
    ii.DESCRIPTION
FROM INTERACTIONSCRIPT ii
WHERE ii.SCRIPTEXISTS = TRUE;


-- get not prepared scripts
SELECT
    ii.NAME,
    ii.DESCRIPTION
FROM INTERACTIONSCRIPT ii
WHERE ii.SCRIPTEXISTS = FALSE;


-- get used scripts
SELECT DISTINCT
    ii.NAME,
    ii.DESCRIPTION,
    ii.SCRIPTEXISTS
FROM INTERACTIONSCRIPT ii
JOIN BALLINTERACTION i ON i.SCRIPT = ii.ID;


-- get not used scripts
SELECT
    ii.NAME,
    ii.DESCRIPTION,
    ii.SCRIPTEXISTS
FROM INTERACTIONSCRIPT ii
LEFT JOIN BALLINTERACTION i ON i.SCRIPT = ii.ID
WHERE i.SCRIPT IS NULL;


-- get missing scripts
SELECT DISTINCT
    ii.NAME,
    ii.DESCRIPTION
FROM INTERACTIONSCRIPT ii
JOIN BALLINTERACTION i ON i.SCRIPT = ii.ID
WHERE ii.SCRIPTEXISTS = FALSE;